version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../step_deployment_package.zip .
      - cd ..
      - zip -g step_deployment_package.zip s3toredshift.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp step_deployment_package.zip s3://lambda-builds-zip-aws/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name copys3toredshift-step --s3-bucket lambda-builds-zip-aws --s3-key step_deployment_package.zip
      - echo "Deployment complete!"